#!/usr/bin/env python3
"""
OpenResilience SMS Alert Service - Interactive Setup Wizard

This script will guide you through the complete setup process.
Just run it and follow the prompts!
"""

import sys
import os
import time
import subprocess
from pathlib import Path


def print_header(text):
    """Print a nice header."""
    print("\n" + "=" * 70)
    print(f"  {text}")
    print("=" * 70)


def print_step(number, title):
    """Print a step header."""
    print(f"\n{'=' * 70}")
    print(f"STEP {number}: {title}")
    print("=" * 70)


def wait_for_user(prompt="Press ENTER to continue..."):
    """Wait for user to press enter."""
    input(f"\n{prompt}")


def check_python():
    """Check Python version."""
    version = sys.version_info
    if version.major < 3 or (version.major == 3 and version.minor < 7):
        print(f"❌ Python {version.major}.{version.minor} is too old!")
        print("   Please install Python 3.7 or higher")
        return False
    print(f"✅ Python {version.major}.{version.minor}.{version.micro}")
    return True


def check_pip():
    """Check if pip is installed."""
    try:
        subprocess.run(['pip', '--version'], capture_output=True, check=True)
        print("✅ pip is installed")
        return True
    except:
        print("❌ pip not found!")
        print("   Install with: python -m ensurepip")
        return False


def install_dependencies():
    """Install required packages."""
    packages = [
        'africastalking',
        'python-dotenv',
        'flask'
    ]
    
    print("\n📦 Installing dependencies...")
    for package in packages:
        print(f"\n  Installing {package}...")
        try:
            subprocess.run(
                ['pip', 'install', package],
                capture_output=True,
                check=True,
                text=True
            )
            print(f"  ✅ {package} installed")
        except subprocess.CalledProcessError as e:
            print(f"  ❌ Failed to install {package}")
            print(f"     Error: {e}")
            return False
    
    return True


def create_env_file():
    """Guide user to create .env file."""
    print_step(2, "Configure Africa's Talking Credentials")
    
    print("\n🔑 You need your Africa's Talking API credentials.")
    print("\nIf you DON'T have them yet:")
    print("  1. Go to: https://account.africastalking.com/auth/register")
    print("  2. Sign up (FREE)")
    print("  3. Go to Sandbox mode")
    print("  4. Settings → API Key → Generate")
    print("  5. Come back here with your credentials")
    
    wait_for_user("\nPress ENTER when you have your API credentials...")
    
    print("\n📝 Enter your credentials:")
    
    # Get username
    print("\nUsername (usually 'sandbox' for testing):")
    username = input("  Username: ").strip()
    if not username:
        username = "sandbox"
    
    # Get API key
    print("\nAPI Key (starts with 'atsk_'):")
    api_key = input("  API Key: ").strip()
    
    if not api_key:
        print("\n❌ API key is required!")
        return False
    
    # Create .env file
    env_content = f"""# Africa's Talking API Credentials
# Generated by setup wizard on {time.strftime('%Y-%m-%d %H:%M')}

AFRICASTALKING_USERNAME={username}
AFRICASTALKING_API_KEY={api_key}
SMS_SHORTCODE=22555
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("\n✅ Created .env file with your credentials")
        return True
    except Exception as e:
        print(f"\n❌ Failed to create .env file: {e}")
        return False


def test_connection():
    """Test connection to Africa's Talking."""
    print_step(3, "Test Connection")
    
    print("\n🧪 Testing connection to Africa's Talking...")
    
    try:
        # Run test script
        result = subprocess.run(
            ['python', 'scripts/test_sms.py'],
            capture_output=True,
            text=True,
            timeout=30
        )
        
        if "✅ ALL TESTS PASSED" in result.stdout:
            print("\n✅ Connection test PASSED!")
            print("\nYour setup is working correctly.")
            return True
        else:
            print("\n⚠️  Some tests may have failed.")
            print("\nOutput:")
            print(result.stdout)
            if result.stderr:
                print("\nErrors:")
                print(result.stderr)
            return False
    except FileNotFoundError:
        print("\n❌ Test script not found!")
        print("   Make sure you're in the openresilience directory")
        return False
    except subprocess.TimeoutExpired:
        print("\n❌ Test timed out!")
        return False
    except Exception as e:
        print(f"\n❌ Test failed: {e}")
        return False


def register_phone():
    """Guide user to register test phone."""
    print_step(4, "Register Your Test Phone Number")
    
    print("\n📱 For SANDBOX mode, you must register your phone number.")
    print("\nSteps:")
    print("  1. Go to: https://account.africastalking.com/apps/sandbox")
    print("  2. Click 'Settings' (left sidebar)")
    print("  3. Click 'SMS' tab")
    print("  4. Scroll to 'Test Phone Numbers'")
    print("  5. Click '+ Add Phone Number'")
    print("  6. Enter YOUR Kenya phone number (+254...)")
    print("  7. Click 'Save'")
    
    wait_for_user("\nPress ENTER after you've registered your phone...")
    
    print("\n✅ Great! Your phone is now registered for testing.")


def send_test_sms():
    """Send test SMS."""
    print_step(5, "Send Test SMS to Your Phone")
    
    print("\n📱 Let's send a REAL SMS to your phone!")
    
    ready = input("\nReady to send test SMS? (yes/no): ").strip().lower()
    
    if ready not in ['yes', 'y']:
        print("\n⏭️  Skipping test SMS")
        return False
    
    try:
        # Run send test script interactively
        subprocess.run(['python', 'scripts/send_test_sms.py'])
        return True
    except FileNotFoundError:
        print("\n❌ Send test script not found!")
        return False
    except KeyboardInterrupt:
        print("\n\n⏭️  Test SMS cancelled")
        return False


def explain_production():
    """Explain production upgrade."""
    print_step(6, "Upgrade to Production (Optional)")
    
    print("\n💼 You're currently in SANDBOX mode (FREE)")
    print("\nSandbox limitations:")
    print("  ❌ Can only send to registered test numbers")
    print("  ❌ Limited to 100 SMS per day")
    print("  ✅ FREE forever")
    
    print("\n🚀 Production mode:")
    print("  ✅ Send to ANY Kenya phone number")
    print("  ✅ Unlimited SMS (pay per use)")
    print("  💰 Cost: ~0.80 KES per SMS (~$0.006 USD)")
    
    print("\nTo upgrade:")
    print("  1. Go to Africa's Talking dashboard")
    print("  2. Click 'Go to Production'")
    print("  3. Top up account (min 1,000 KES)")
    print("  4. Get new production API key")
    print("  5. Update your .env file")
    
    print("\n💡 TIP: Stay in sandbox for testing, upgrade when ready to launch")


def explain_shortcode():
    """Explain shortcode application."""
    print_step(7, "Apply for Shortcode 22555 (Recommended)")
    
    print("\n📞 What's a shortcode?")
    print("  A 5-digit number like '22555' that's easy to remember")
    
    print("\nWithout shortcode:")
    print("  Farmers SMS to: +254712345678 ❌ (hard to remember)")
    
    print("\nWith shortcode:")
    print("  Farmers SMS to: 22555 ✅ (easy!)")
    
    print("\n💰 Cost:")
    print("  Shared shortcode: ~5,000 KES/month (~$40 USD)")
    print("  Dedicated shortcode: ~50,000 KES/month (~$400 USD)")
    
    print("\n📧 To apply:")
    print("  Email: solutions@africastalking.com")
    print("  Subject: 'Shortcode Application - OpenResilience Kenya'")
    print("  Include:")
    print("    - Organization name")
    print("    - Use case (water alerts for farmers)")
    print("    - Expected monthly SMS volume")
    
    print("\n⏱️  Timeline: 2-4 weeks approval")
    
    print("\n💡 TIP: Start WITHOUT shortcode, add later when scaling")


def explain_webhook():
    """Explain webhook setup."""
    print_step(8, "Set Up Webhook (For Incoming SMS)")
    
    print("\n🔗 What's a webhook?")
    print("  When farmer sends 'MAJI' to your number →")
    print("  Africa's Talking calls YOUR server →")
    print("  Your server processes command →")
    print("  Sends confirmation SMS")
    
    print("\n🖥️  To set up webhook:")
    print("  1. Deploy webhook.py to a server:")
    print("     Option A: Heroku (easiest)")
    print("     Option B: DigitalOcean")
    print("     Option C: Your own server")
    
    print("\n  2. Configure in Africa's Talking:")
    print("     Dashboard → SMS → Settings → Callback URL")
    print("     Enter: https://your-server.com/sms/callback")
    
    print("\n🧪 For local testing:")
    print("  1. Install ngrok: brew install ngrok")
    print("  2. Run webhook: python webhook.py")
    print("  3. Expose publicly: ngrok http 5000")
    print("  4. Use ngrok URL in Africa's Talking")
    
    print("\n💡 TIP: Start without webhook (manual subscriptions), add later")


def show_next_steps():
    """Show what to do next."""
    print_header("🎉 SETUP COMPLETE!")
    
    print("\n✅ What you've accomplished:")
    print("  ✓ Installed dependencies")
    print("  ✓ Configured Africa's Talking credentials")
    print("  ✓ Tested connection")
    print("  ✓ (Optional) Sent test SMS")
    
    print("\n🚀 Next steps to go live:")
    print("\n1. TEST MORE:")
    print("   python scripts/send_test_sms.py")
    
    print("\n2. UPGRADE TO PRODUCTION (when ready):")
    print("   - Top up Africa's Talking account")
    print("   - Get production API key")
    print("   - Update .env file")
    
    print("\n3. DEPLOY WEBHOOK (for auto-subscriptions):")
    print("   - Deploy webhook.py to Heroku/server")
    print("   - Configure callback URL in Africa's Talking")
    
    print("\n4. APPLY FOR SHORTCODE (recommended):")
    print("   - Email solutions@africastalking.com")
    print("   - Get 22555 shortcode")
    
    print("\n5. SEND WEEKLY ALERTS:")
    print("   python scripts/send_weekly_alerts.py")
    print("   (Schedule with cron: 0 8 * * 0)")
    
    print("\n📚 Documentation:")
    print("   docs/SMS_SETUP.md - Complete guide")
    
    print("\n💡 Support:")
    print("   - Africa's Talking: support@africastalking.com")
    print("   - GitHub Issues: Report problems")
    
    print("\n" + "=" * 70)


def main():
    """Main setup wizard."""
    print_header("OpenResilience Kenya - SMS Alert Service Setup Wizard")
    
    print("\n👋 Welcome! This wizard will help you set up SMS alerts.")
    print("\nWhat you'll need:")
    print("  📧 Email address (for Africa's Talking account)")
    print("  📱 Kenya phone number (for testing)")
    print("  ⏱️  10-15 minutes")
    
    wait_for_user()
    
    # Step 1: Check requirements
    print_step(1, "Check Requirements")
    
    if not check_python():
        return
    
    if not check_pip():
        return
    
    # Install dependencies
    if not install_dependencies():
        print("\n❌ Failed to install dependencies!")
        print("   Try manually: pip install africastalking python-dotenv flask")
        return
    
    # Step 2: Create .env file
    if not create_env_file():
        return
    
    # Step 3: Test connection
    if not test_connection():
        print("\n⚠️  Connection test had issues, but you can continue...")
        proceed = input("Continue anyway? (yes/no): ").strip().lower()
        if proceed not in ['yes', 'y']:
            return
    
    # Step 4: Register phone
    register_phone()
    
    # Step 5: Send test SMS
    send_test_sms()
    
    # Step 6-8: Explain next steps
    explain_production()
    explain_shortcode()
    explain_webhook()
    
    # Show summary
    show_next_steps()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Setup cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Setup failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
