"""
Data Export Utilities for OpenResilience

Provides CSV, Excel, and summary report exports for:
- NGO administrators needing data for analysis
- County governments preparing reports
- Researchers conducting studies
"""

import pandas as pd
from datetime import datetime
from typing import Dict, Any, List
import io


def export_county_data_csv(df: pd.DataFrame) -> bytes:
    """
    Export county data to CSV format.
    
    Args:
        df: DataFrame with county resilience data
    
    Returns:
        CSV file as bytes
    """
    # Create buffer
    buffer = io.StringIO()
    
    # Write CSV
    df.to_csv(buffer, index=False)
    
    # Get bytes
    return buffer.getvalue().encode('utf-8')


def export_county_summary_report(
    county_name: str,
    county_data: Dict[str, Any],
    timestamp: datetime
) -> str:
    """
    Generate human-readable summary report for a county.
    
    Args:
        county_name: County name
        county_data: Dict with all county metrics
        timestamp: Report generation time
    
    Returns:
        Formatted text report
    """
    # Convert Severity number to risk level text
    severity = county_data.get('Severity', 0)
    risk_level_map = {
        3: "🔴 CRITICAL",
        2: "🟠 HIGH",
        1: "🟡 MODERATE",
        0: "🟢 LOW"
    }
    risk_level = risk_level_map.get(severity, "Unknown")
    
    report = f"""
OPENRESILIENCE KENYA - COUNTY SUMMARY REPORT
{'=' * 60}

County: {county_name}
Generated: {timestamp.strftime('%Y-%m-%d %H:%M EAT')}
Data Source: Live Satellite Data (NASA IMERG + SMAP + Earth Engine MODIS)

RESILIENCE INDICES
{'=' * 60}
Water Stress Index (WSI):     {county_data.get('WSI', 0):.1%}
Food Stress Index (FSI):      {county_data.get('FSI', 0):.1%}
Market Stress Index (MSI):    {county_data.get('MSI', 0):.1%}
Composite Resilience (CRI):   {county_data.get('CRI', 0):.1%}

RISK ASSESSMENT
{'=' * 60}
Risk Level: {risk_level}
ASAL Classification: {'Yes' if county_data.get('ASAL', 'No') == 'Yes' else 'No'}

SATELLITE OBSERVATIONS
{'=' * 60}
Rainfall Anomaly: {county_data.get('rainfall_anomaly', 0):+.1f}% from normal
Soil Moisture: {county_data.get('soil_moisture', 0):.2f} (0-1 scale)
Vegetation Health: {county_data.get('vegetation_health', 0):.2f} (0-1 scale)

FORECAST (Next 3 Months)
{'=' * 60}
1-2 Months: {county_data.get('Forecast_1_2mo', 0):.0%} stress expected
3-6 Months: {county_data.get('Forecast_3_6mo', 0):.0%} stress expected

POPULATION DATA
{'=' * 60}
Population: {county_data.get('Population', 0):,}
Current Stress Level: {county_data.get('Current_Stress', 0):.0%}

RECOMMENDATIONS
{'=' * 60}
"""
    
    # Add recommendations based on severity level
    # Severity: 3=CRITICAL, 2=HIGH, 1=MODERATE, 0=LOW
    
    if severity >= 3:
        report += """
⚠️  URGENT ACTION REQUIRED:
- Activate emergency water distribution
- Coordinate with NDMA for food relief
- Prioritize vulnerable communities
- Deploy water trucking immediately
- Consider livestock destocking programs
"""
    elif severity == 2:
        report += """
⚡ HIGH PRIORITY ACTIONS:
- Increase monitoring frequency
- Pre-position emergency supplies
- Alert community health workers
- Prepare water rationing plans
- Issue agricultural advisories
"""
    elif severity == 1:
        report += """
📊 STANDARD MONITORING:
- Continue routine monitoring
- Maintain water reserves
- Support farmers with seasonal advice
- Monitor vulnerable areas closely
"""
    else:
        report += """
✅ NORMAL CONDITIONS:
- Routine monitoring adequate
- Focus on preparedness activities
- Update contingency plans
- Conduct community training
"""
    
    report += f"""

{'=' * 60}
Report Generated by OpenResilience Kenya
Data Sovereignty: Community-owned, locally-managed
Contact: {county_name} County Water Office / NDMA
{'=' * 60}
"""
    
    return report


def export_all_counties_excel(df: pd.DataFrame) -> bytes:
    """
    Export all counties data to Excel with multiple sheets.
    
    Args:
        df: DataFrame with all county data
    
    Returns:
        Excel file as bytes
    """
    buffer = io.BytesIO()
    
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        # Main data sheet
        df.to_excel(writer, sheet_name='All Counties', index=False)
        
        # ASAL counties only
        if 'ASAL' in df.columns:
            asal_df = df[df['ASAL'] == 'Yes']
            asal_df.to_excel(writer, sheet_name='ASAL Counties', index=False)
        
        # High risk counties (Severity >= 2 means HIGH or CRITICAL)
        if 'Severity' in df.columns:
            high_risk = df[df['Severity'] >= 2]
            high_risk.to_excel(writer, sheet_name='High Risk', index=False)
        
        # Summary statistics
        summary_data = {
            'Metric': ['Average WSI', 'Average FSI', 'Average MSI', 'Average CRI', 
                      'Counties in Critical Risk (Severity 3)', 'Counties in High Risk (Severity 2+)',
                      'Total Population Affected', 'ASAL Counties'],
            'Value': [
                f"{df['WSI'].mean():.1%}" if 'WSI' in df.columns else 'N/A',
                f"{df['FSI'].mean():.1%}" if 'FSI' in df.columns else 'N/A',
                f"{df['MSI'].mean():.1%}" if 'MSI' in df.columns else 'N/A',
                f"{df['CRI'].mean():.1%}" if 'CRI' in df.columns else 'N/A',
                len(df[df['Severity'] == 3]) if 'Severity' in df.columns else 'N/A',
                len(df[df['Severity'] >= 2]) if 'Severity' in df.columns else 'N/A',
                f"{df[df['Severity'] >= 2]['Population'].sum():,}" if 'Population' in df.columns and 'Severity' in df.columns else 'N/A',
                len(df[df['ASAL'] == 'Yes']) if 'ASAL' in df.columns else 'N/A'
            ]
        }
        summary_df = pd.DataFrame(summary_data)
        summary_df.to_excel(writer, sheet_name='Summary', index=False)
    
    buffer.seek(0)
    return buffer.getvalue()


def export_field_reports_csv(reports: List[Dict]) -> bytes:
    """
    Export field reports to CSV.
    
    Args:
        reports: List of field report dictionaries
    
    Returns:
        CSV file as bytes
    """
    if not reports:
        # Return empty CSV with headers
        df = pd.DataFrame(columns=['Timestamp', 'County', 'Location', 'Type', 'Description', 'Status'])
    else:
        df = pd.DataFrame(reports)
    
    buffer = io.StringIO()
    df.to_csv(buffer, index=False)
    return buffer.getvalue().encode('utf-8')


# Export functions
__all__ = [
    'export_county_data_csv',
    'export_county_summary_report',
    'export_all_counties_excel',
    'export_field_reports_csv'
]
